import React from 'react';
import styled from 'styled-components';
import {Element} from 'react-scroll';

export default () => (
  <Element id="faq" name="faq">
    <div className="container">
      <Container>
        <div className="row">
          <div className="col-12">
            <div className="title">FAQ</div>
          </div>
        </div>
        <div className="row">
          <div className="col-12">
            <div className="question">
              {' '}
              Can you somehow influence the outcome of the game?
            </div>
          </div>
          <div className="offset-1 col-10">
            <div className="answer">
              Neither the administration nor any other person related to the
              site has an opportunity to influence the outcome of your game. Our
              project is based on the open platform, and the code is publicly
              available (link to our smart contract), which excludes any
              interference from our side.
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-12">
            <div className="question">
              What makes us different from other sites?{' '}
            </div>
          </div>
          <div className="offset-1 col-10">
            <div className="answer">
              Our project has a fixed percentage, regardless of the minimum and
              maximum rates, which excludes various "floating" interest and you
              know in advance how your rate is distributed. The goal of our
              project is to popularize the gambling segment on the Etherium
              platform, so our team will constantly add to our project the
              entire variety of games that use smart contracts.
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-12">
            <div className="question">
              What's the catch? Explain how it works!
            </div>
          </div>
          <div className="offset-1 col-10">
            <div className="answer">
              Well, we’ll have to go into the technical details a bit
              <br />
              - Scramblegamble.net makes a number and sends you its hash. <br />
              - You send a transaction with your rate and the hash of the number
              from the previous step. <br />
              - Note that Scramblegamble.net has already “subscribed” to this
              number, even before your bet. <br />
              - When a transaction is confirmed by the network, the smart
              contract remembers the bid details and hash numbers. <br />
              - Our bot-croupier opens the hidden number by sending it as a
              separate transaction. <br />
              - A smart contract accepts a transaction if and only if the hash
              of the sent number matches the memorized one. <br />
              - The smart contract 'mixes' the number and the block hash of the
              bet to get a random number. <br />- The resulting number is used
              to determine the outcome of the bet. In case of winning, the smart
              contract sends you the Ether. <br />
            </div>
          </div>
        </div>
        <div className="row">
          <div className="col-12">
            <div className="question">
              Can Scramblegamble.net influence the outcome?
            </div>
          </div>
          <div className="offset-1 col-10">
            <div className="answer">
              No, since the contract remembers the hash of the number, which
              means Scramblegamble.net cannot change it afterwards. The “mixing”
              of a number with a block hash makes it impossible to influence the
              result by the miners. On the other hand, Scramblegamble.net cannot
              influence the result (despite the fact that the numbers are
              generated by our server), since we cannot predict block hashes.
              Everything described above is the well-known 'commitment scheme',
              thanks to which Scramblegamble.net provides a high-quality random
              number generator that allows you to play high, maintain the
              jackpot and at the same time maintain transparency.
            </div>
          </div>
        </div>
      </Container>
    </div>
  </Element>
);

const Container = styled.div`
  padding: 100px 0;
  .title {
    width: 100%;
    text-align: center;
    font-size: 50px;
    font-weight: 1000;
    margin-bottom: 20px;
  }
  .question {
    margin-top: 30px;
    color: red;
    font-weight: bold;
    font-size: 25px;
  }
  .answer {
    font-size: 18px;
    letter-spacing: 0.5px;
    margin-top: 10px;
  }
`;
